# Generated by Django 6.1 on 2026-08-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorUña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo_color', models.CharField(help_text='Código hexadecimal ej: #FFB6C1', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='DisenoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_extra', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='disenos_personalizados/')),
            ],
        ),
        migrations.CreateModel(
            name='FormaUña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='formas/')),
            ],
        ),
    ]
