# Generated by Django 6.1 on 2026-08-20 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20, unique=True, verbose_name='Día')),
                ('apertura', models.TimeField(verbose_name='Hora de apertura')),
                ('cierre', models.TimeField(verbose_name='Hora de cierre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('instagram', models.CharField(blank=True, max_length=50, verbose_name='Instagram')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('confirmada', '✅ Confirmada'), ('completada', '💅 Completada'), ('cancelada', '❌ Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('diseno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.diseno', verbose_name='Diseño')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
