# Generated by Django 6.1 on 2026-08-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('calificacion', models.PositiveIntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5, verbose_name='Calificación')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='resenas/', verbose_name='Foto de tus uñas')),
                ('aprobada', models.BooleanField(default=False, verbose_name='Aprobada')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-creada_en'],
            },
        ),
    ]
